### ISSUE TITLE
Only change one region of the sequence? 

### ISSUE THREAD

**Issue by collinskatie** [johli/seqprop#2]
Hi, 

Thank you again so much for your awesome software! I was wondering if there's a way to only modify a region of the seed sequence when running gradient ascent (i.e. of a 60 nt sequence, only update the first 30 nt and leave the rest unchanged)? Is there an option for this or a way to incorporate into the loss function? 

Thanks for your help!

**Comment by johli** [comment]
Hi,

I'm glad you're finding the package useful!

Just to clarify, this is how I interpret what you want to do: Your predictor model takes 60nt sequences as input. You would like to only optimize the first 30nt of the sequence and leave the remaining 30nt fixed at some constant onehot-coded sequence content.

If the above is incorrect, could you help me understand a little better what it is you're after?

If the above is correct, then yes, that functionality is implemented in the package :)! Overly long explanation follows:

The **build_generator**-function of the **seqprop.generator** module takes two keyword arguments you should use to achieve this:
**sequence_templates** - This parameter expects a list of "sequence templates", one for as many sequences you are optimizing (the n_sequences parameter), of course you can set all sequence templates to be identical if you want to optimize many instances with different random inits.

Each sequence template is a string of, in your case, 60nt. The letters A/C/G/T specifies that you wish to lock that specific base position at a constant, non-changeable nucleotide. The letter N specifies that this base position should be optimized by SeqProp, and will either be initialized randomly or by the **init_sequences**-parameter (see below). The letter X specifies that the base position should be uniformly initialized (0.25 on all nucleotides) but not optimizable.

E.g. "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNACGTTACGTTACGTTACGTTXXXXXXXXXX" means the first 30nt are optimized by SeqProp, the next 20nt are locked at sequence ACGTTACGTTACGTTACGTT and the final 10nt are uniform 0.25-bases.

See the following notebooks for examples on how to use this parameter:
1. https://nbviewer.jupyter.org/github/johli/seqprop/blob/master/examples/apa/seqprop_aparent_isoform_optimization.ipynb
2. https://nbviewer.jupyter.org/github/johli/seqprop/blob/master/examples/apa/seqprop_aparent_cleavage_optimization_init_sequences.ipynb

**init_sequences** -  In the second example notebook, we are using both the **sequence_templates** and **init_sequences** parameters together. The **init_sequences** parameter specifies what to initialize the optimizable bases  (The 'N'-letters) to in your sequence template. If **init_sequences** is not set, the 'N'-letters are randomly and uniformly initialized between -0.2 and +0.2 in logprob space. The letter 'X' in **init_sequence** tells SeqProp that this base position should be randomly uniformly initialized (or whatever constant sequence is in the corresponding position on the sequence template).

E.g. "AAAAAAAAAAAAAAAAAAAAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" means the first 20nt should be initialized to A:s, and the next 40nt should be initialized to whatever is in the sequence template (i.e., constant sequence if that's in the sequence template or randomly if the corresponding bases are 'N'-letters).

Let me know if it feels unclear or if you have follow up questions, I'm happy to help :)!

Best,

Johannes

**Comment by collinskatie** [comment]
Hi Johannes, 

Thank you for your detailed response! That is incredibly helpful. 

Building off of my last question, do you have any functionality built-into SeqProp where you only change the first 30 nucleotides of a 60 nt sequence and part of the remaining un-optimized 30 nt are changed dynamically to be the reverse complement of part of the first 30 nts? 

i.e. in the above example you gave: NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNACGTTACGTTACGTTACGTTXXXXXXXXXX - the Xs are the reverse complement of nucleotides 10 thru 20 in the N region of the first 30 nt? 

To rephrase my question: is there a way to only optimize part of the sequence, but dynamically change part of the sequence or template in response to changes in the first part? Or would this be something best put in a custom loss function? 

Thanks again for your help and for this fantastic resource!

**Comment by johli** [comment]
Hi Katie,

The SeqProp package should now have support for what you're after! I added a generalized parameter where you can supply any custom transform function between the generator and predictor to transform the PWM (or Sampled Onehot), for example to reverse complement parts of it.

Specifically, I updated the **build_generator**-function with a new keyword parameter, **pwm_transform_func**, which expects one lambda function (same style as how you define the loss function). This function should take the PWM as input and return the transformed PWM, which in turn will be passed to the predictor.

Please see the notebook example I added at: https://nbviewer.jupyter.org/github/johli/seqprop/blob/master/examples/basic/seqprop_basic_sequence_transform.ipynb

Here I use a very simple dummy "Predictor model" that simply scores the number of "GTT" motifs in the optimized sequence, and the loss function simply tries to maximize that score. I.e., instead of having the complex APA model I went with a simpler predictor to keep the example concise.

The **get_revcomp_transform**-function is where I define the sequence transform that takes the first 30nt of the optimized PWM, reverse complements it, and appends it as the next 30nt of the sequence (hopefully this is similar to how you wanted to use it?). The **get_revcomp_transform_opt**-function is an optimized version of this function, if you want it.

Let me know if the added functionality is enough for your needs, or if there is more you want added! Also let me know if you experience any bugs with it, I haven't tested it extensively yet.

Best,

Johannes

**Comment by collinskatie** [comment]
Awesome!! Thank you so much! That is perfect. 

Thank you again! 

Best, 

Katie

**Comment by johli** [comment]
Perfect, glad it helped :)!

Let me know if you have any other suggested improvements, I’d be happy to implement them.

Best,

Johannes
