### ISSUE TITLE
Problem with visualization for dragoNN examples

### ISSUE THREAD

**Issue by pythonLoader** [johli/seqprop#3]
Hello,

Thanks for this great software. I was trying to reproduce the results for the dragoNN experiments. In all cases, I am receiving the following error: 

`Traceback (most recent call last):
  File "dragonn_run.py", line 418, in <module>
    valid_monitor.plot_metrics_and_pwm(fig_name=fig_name)
  File "/home/sawmya/miniconda3/envs/seqprop/lib/python3.6/site-packages/seqprop-0.1-py3.6.egg/seqprop/visualization/seqprop_visualization.py", line 601, in plot_metrics_and_pwm
AttributeError: 'FlexibleSeqPropMonitor' object has no attribute 'cached_pred_bundle`

Any idea why it might be happening?

**Comment by johli** [comment]
Hi,

Sorry for the late response. I've now had time to go through the code and replicate the issue.

I think you are probably instantiating the FlexibleSeqPropMonitor without the predictor argument. Unfortunately the predictor parameter is erroneously specified as an optional keyword but it is in fact required to use the monitor. In this example notebook (https://github.com/johli/seqprop/blob/master/examples/dragonn/seqprop_dragonn_optimization_eval_instancenorm_earthmover.ipynb), I explicitly construct a validation model with this line of code:

_, valid_predictor = build_predictor(valid_generator, load_saved_predictor(model_path, library_context=None), n_sequences=n_sequences, n_samples=n_valid_samples, eval_mode='sample')

And then construct the Monitor object by passing the argument 'predictor=valid_predictor' in the constructor:

valid_monitor = FlexibleSeqPropMonitor(predictor=valid_predictor, ...)

The 'valid_predictor' model object is constructed as a wrapper around SeqProp in order to get both the currently optimized PWM and the corresponding sample fitness predictions from the predict step. Hopefully you can use the example code to instantiate the valid_predictor as is done in the notebook, let me know if you run into further issues.

Best,

Johannes
